# Site settings
title: ryanbran.ch
author: "Ryan Branch"
description: >- # this means to ignore newlines until "baseurl:"
  Ryan Branch is an engineer and scientific researcher from Michigan.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ryanbran.ch" # the base hostname & protocol for your site, e.g. http://example.com
# Contact-related
email: contact.ryanbran.ch@gmail.com
github_username:  ryanbranch
github_gist: true
linkedin_username: ryanbranch
twitter_username: rjbranch
discord_username: "RyanBranch"
discord_tag: "4020"
orcid_id: "0000-0001-6456-3468"
google_scholar_id: "tkVpzE4AAAAJ"
# Contact Form Configuration
captcha: true
captcha_public_key: "6LfKERAaAAAAAAMK-xtUAzzqNsAN0JChys7JqubW"
formspree_endpoint_contact: "xbjpgbvy"
formspree_endpoint_privacy: "mgepzwpo"

# Static Page Permalinks
# NOTE: MUST BE UPDATED TO MATCH THE PERMALINKS SET IN THE FRONT MATTER OF EACH RELEVANT PAGE
permalink_portfolio: "/portfolio/"
permalink_software_projects: "/software/"
permalink_hardware_projects: "/hardware/"
permalink_research: "/research/"
permalink_contact: "/contact/"

# File Object Permalinks
# MEDIA
permalink_icon_github: "https://data.ryanbran.ch/media/social-icons/icon-github-black-128px.png"
permalink_icon_linkedin: "https://data.ryanbran.ch/media/social-icons/icon-linkedin-black-128px.png"
permalink_icon_orcid: "https://data.ryanbran.ch/media/social-icons/icon-orcid-black-128px.png"
# DOCUMENTS
# Portfolio
permalink_pdf_cv: "https://data.ryanbran.ch/portfolio/ryanbranch-cirriculum-vitae.pdf"
permalink_pdf_resume: "https://data.ryanbran.ch/portfolio/ryanbranch-resume.pdf"

# Special Characters
right_arrow: "&#9656;"

# Google-related
google_analytics: false
#google_analytics_tracking_id: "UA-158059409-4"
google_fonts: false
# Display Toggles
footer_email: false

# COLLECTIONS
# See the Jekyll documentation for more info: https://jekyllrb.com/docs/collections/
collections:
  page_types:
    output: false 
  portfolio_items:
    output: true
    order:
      resume.html
      projects/project-1.html


# Build settings
markdown: kramdown
# Commented out the line below in order to use jekyanbranch as the base theme
#theme: minima
remote_theme: ryanbranch/jekyanbranch@main
plugins:
  - jekyll-feed
  # Added to support the use of http://github.com/ryanbranch/jekyanbranch
  # as a theme DURING LOCAL DEVELOPMENT. This line is not needed in order
  # for a GitHub Pages repo to use another GitHub repo as a Jekyll theme.
  - jekyll-remote-theme
  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - personal/
  - sandbox/
